o'zgeris kiritildi
apertium/apertium-uzb-kaa pull request #10
Opened 2021-04-26 18:32 UTC by Zigfruid

Taza so'zlerde qosildi

2021-04-27 01:05 UTC, jonorthwash requested changes

2021-04-27 01:05 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>bor<s n="n"/></l>                      <r>bar<s n="n"/></r></p></e>
Yaq, bul "bar" degen sóz emes, sol "adj" boladı.  Bul "bor" degen zat esim (мел degen) bolsa kerek.  Solay bolıwı múmkinbe?

2021-04-27 01:05 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>soʻradi<s n="v"/><s n="tv"/></l>         <r>soradi<s n="v"/><s n="tv"/></r></p></e>
Formalar kirgizilmeydi, túbirler (корни) ǵana.

2021-04-27 01:05 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>kelayapdi<s n="n"/></l>                  <r>kiyatir<s n="n"/></r></p></e>
Formalar bolmaydı.

2021-04-27 01:05 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qayerdaligini<s n="n"/></l>               <r>qay jerde ekenin<s n="n"/></r></p></e>
Formalar bolmaydı.

2021-04-27 01:05 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tugatgandan<s n="n"/></l>                 <r>tawsıwdan<s n="n"/></r></p></e>
Formalar bolmaydı.

2021-04-27 09:25 UTC, Zigfruid commented
Assalawma aleykum,
Qalaysiz?
Qaraqalpaq tilinde "bor" degen so'z joq, bar, boladi, biraq "chalk" - "por"
boladi.
Joqarida islegenlerim qa'te ma onda? 😥😥😥

вт, 27 апр. 2021 г. в 06:05, Jonathan Washington ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In apertium-uzb-kaa.uzb-kaa.dix
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#discussion_r620754027>
> :
>
> > @@ -2868,7 +2869,7 @@
>
>  <e>       <p><l>boqim<s n="n"/></l>                    <r>qaraw<s n="n"/></r></p></e>
>
>  <e>       <p><l>boqimsiz<s n="adj"/></l>               <r>jetim<s n="adj"/></r></p></e>
>
>  <e>       <p><l>boqish<s n="v"/><s n="tv"/><s n="coop"/></l><r>qaraw<s n="v"/><s n="tv"/><s n="coop"/></r></p></e>
>
> -<e>       <p><l>bor<s n="n"/></l>                      <r>bor<s n="n"/></r></p></e>
>
> +<e>       <p><l>bor<s n="n"/></l>                      <r>bar<s n="n"/></r></p></e>
>
>
> Yaq, bul "bar" degen sóz emes, sol "adj" boladı. Bul "bor" degen zat esim
> (мел degen) bolsa kerek. Solay bolıwı múmkinbe?
> ------------------------------
>
> In apertium-uzb-kaa.uzb-kaa.dix
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#discussion_r620754945>
> :
>
> > @@ -711,6 +711,7 @@
>
>  <e>       <p><l>”<s n="rquot"/></l>                    <r>”<s n="rquot"/></r></p></e>
>
>  <e>       <p><l>sol<s n="adj"/></l>                    <r>sol<s n="adj"/></r></p></e>
>
>  <e>       <p><l>soʻra<s n="v"/><s n="tv"/></l>         <r>sora<s n="v"/><s n="tv"/></r></p></e>
>
> +<e>       <p><l>soʻradi<s n="v"/><s n="tv"/></l>         <r>soradi<s n="v"/><s n="tv"/></r></p></e>
>
>
> Formalar kirgizilmeydi, túbirler (корни) ǵana.
> ------------------------------
>
> In apertium-uzb-kaa.uzb-kaa.dix
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#discussion_r620755201>
> :
>
> > @@ -5180,6 +5182,7 @@
>
>  <e>       <p><l>keksa<s n="adj"/></l>                  <r>ǵarrı<s n="adj"/></r></p></e>
>
>  <e>       <p><l>keksalik<s n="n"/></l>                 <r>ǵarrılıq<s n="n"/></r></p></e>
>
>  <e>       <p><l>kelajak<s n="n"/></l>                  <r>keleshek<s n="n"/></r></p></e>
>
> +<e>       <p><l>kelayapdi<s n="n"/></l>                  <r>kiyatir<s n="n"/></r></p></e>
>
>
> Formalar bolmaydı.
> ------------------------------
>
> In apertium-uzb-kaa.uzb-kaa.dix
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#discussion_r620755373>
> :
>
> > @@ -14346,6 +14349,7 @@
>
>  <e>       <p><l>qayoqqadir<s n="n"/></l>               <r>qayaqqadir<s n="n"/></r></p></e>
>
>  <e>       <p><l>qayerdagi<s n="n"/></l>                <r>qay jerdegi<s n="n"/></r></p></e>
>
>  <e>       <p><l>qayerdalik<s n="n"/></l>               <r>qay jerdelik<s n="n"/></r></p></e>
>
> +<e>       <p><l>qayerdaligini<s n="n"/></l>               <r>qay jerde ekenin<s n="n"/></r></p></e>
>
>
> Formalar bolmaydı.
> ------------------------------
>
> In apertium-uzb-kaa.uzb-kaa.dix
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#discussion_r620755485>
> :
>
> > @@ -16707,6 +16711,7 @@
>
>  <e>       <p><l>transsendentalizm<s n="n"/></l>        <r>transsendentalizm<s n="n"/></r></p></e>
>
>  <e>       <p><l>truppala<s n="v"/><s n="tv"/></l>      <r>truppala<s n="v"/><s n="tv"/></r></p></e>
>
>  <e>       <p><l>tuflash<s n="v"/><s n="iv"/><s n="coop"/></l><r>túpiriw<s n="v"/><s n="iv"/><s n="coop"/></r></p></e>
>
> +<e>       <p><l>tugatgandan<s n="n"/></l>                 <r>tawsıwdan<s n="n"/></r></p></e>
>
>
> Formalar bolmaydı.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#pullrequestreview-645254385>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQHAXEANLY7U3ZZCYOJ5Q3TKYEWPANCNFSM43TNPIDA>
> .
>

2021-04-28 04:47 UTC, jonorthwash commented
> Assalawma aleykum, Qalaysiz? Qaraqalpaq tilinde "bor" degen so'z joq, bar, boladi, biraq "chalk" - "por" boladi. Joqarida islegenlerim qa'te ma onda? 

Solay bolsa, onda bul qatardı alıp salıwġa boladı.

Ózbekshe bor, Qaraqalpaqsha bar degen sóz sın esim bolıp "adj" dep sanalıw kerek.  Onday qatar joq bolsa, bul qatardı "n"den ózgertiwge boladı.

2021-05-01 21:27 UTC, jonorthwash requested changes
Daǵı bir nárse: `.hfst` jáne `.rlx` fayllardı qospaw kerek.

2021-05-01 21:27 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>bor<s n="n"/></l>                      <r>bar<s n="n"/></r></p></e>
Men teksersem ózbekshe bo'r dedi eken.  Durıs «'» simvolın qollanıwǵa abay bolıń.

2021-05-01 21:27 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>hursand<s n="adj"/></l>           <r>quwanıshlı<s n="n"/></r></p></e>
Qaraqalpaqsha bul sın esim, zat esim emes, durıspa?

2021-05-02 15:40 UTC, Zigfruid commented
Hursand деген соз adjective - куанышлы(келбетлик - кандай деген сорауга
жуап берсе), деген манисти билдиреди,
bo'r - деген verb болган жагдайда "бир жерге барып кайт", "бир жерге бару"
деген манисте болады каракалпак тилинде

вс, 2 мая 2021 г. в 02:27, Jonathan Washington ***@***.***>:

> ***@***.**** requested changes on this pull request.
>
> Daǵı bir nárse: .hfst jáne .rlx fayllardı qospaw kerek.
> ------------------------------
>
> In apertium-uzb-kaa.uzb-kaa.dix
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#discussion_r624568021>
> :
>
> > @@ -4391,6 +4391,7 @@
>
>  <e>       <p><l>hurmatsizlik<s n="n"/></l>             <r>húrmetsizlik<s n="n"/></r></p></e>
>
>  <e>       <p><l>hurriyat<s n="n"/></l>                 <r>azatlıq<s n="n"/></r></p></e>
>
>  <e>       <p><l>hurriyatparvar<s n="n"/></l>           <r>azatlıqparvar<s n="n"/></r></p></e>
>
> +<e>       <p><l>hursand<s n="adj"/></l>           <r>quwanıshlı<s n="n"/></r></p></e>
>
>
> Qaraqalpaqsha bul sın esim, zat esim emes, durıspa?
> ------------------------------
>
> In apertium-uzb-kaa.uzb-kaa.dix
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#discussion_r624567966>
> :
>
> > @@ -2868,7 +2869,7 @@
>
>  <e>       <p><l>boqim<s n="n"/></l>                    <r>qaraw<s n="n"/></r></p></e>
>
>  <e>       <p><l>boqimsiz<s n="adj"/></l>               <r>jetim<s n="adj"/></r></p></e>
>
>  <e>       <p><l>boqish<s n="v"/><s n="tv"/><s n="coop"/></l><r>qaraw<s n="v"/><s n="tv"/><s n="coop"/></r></p></e>
>
> -<e>       <p><l>bor<s n="n"/></l>                      <r>bor<s n="n"/></r></p></e>
>
> +<e>       <p><l>bor<s n="n"/></l>                      <r>bar<s n="n"/></r></p></e>
>
>
> Men teksersem ózbekshe bo'r dedi eken. Durıs «'» simvolın qollanıwǵa abay
> bolıń.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#pullrequestreview-649819581>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQHAXHCENHOPNNW7FJTIXTTLRW5TANCNFSM43TNPIDA>
> .
>

2021-05-02 20:50 UTC, jonorthwash commented
> Hursand деген соз adjective - куанышлы(келбетлик - кандай деген сорауга жуап берсе), деген манисти билдиреди, 

Biraq bul jerde `"n"` dep jazılıp turadı, "adj" bolıw kerek.

> bo'r - деген verb болган жагдайда "бир жерге барып кайт", "бир жерге бару" деген манисте болады каракалпак тилинде 

Bo'r (chalk), bor (go) jáne bor (есть) úsh basqa sóz.  Birinshisi "n", ekinshisi "v", úshinshisi "adj".  Sózlikte (`.dix` faylında) solay bolıw kerek.

2021-05-08 01:20 UTC, jonorthwash commented
Bul nárselerdi jónleysizbe?

2021-05-08 06:50 UTC, Zigfruid commented
Ассалаума алейкум,

калайсыз?
ауа дурслайман, кеше 1-2 кун ауырынкырап калып едим,
кеширерсиз

сб, 8 мая 2021 г. в 06:21, Jonathan Washington ***@***.***>:

> Bul nárselerdi jónleysizbe?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apertium/apertium-uzb-kaa/pull/10#issuecomment-834932355>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOQHAXA7GNUCXH2XGFCRCQLTMSGYHANCNFSM43TNPIDA>
> .
>

2021-06-18 18:37 UTC, closed without merging