o'zgeris kiritildi
apertium/apertium-uzb-kaa pull request #11
Opened 2021-06-20 16:41 UTC by Zigfruid

2021-06-29 19:00 UTC, jonorthwash requested changes

2021-06-29 19:00 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>bor<s n="v"/></l>                      <r>bar<s n="n"/></r></p></e>
Bul nadurıs sıyaqlı.  `bor<v><iv>` = `bar<v><iv>` bolıw kerekǵo.

2021-06-29 19:00 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>hursand<s n="adj"/></l>           <r>quwanıshlı<s n="n"/></r></p></e>
Bos orınlardı teń qıla alasızba?

2021-06-29 19:00 UTC, jonorthwash commented on uzb-kaa.rlx
> +DELIMITERS = "<.>" "<!>" "<?>" ;
Bul fayl PRda bolmaw kerek.

2021-07-02 12:34 UTC, Zigfruid commented on uzb-kaa.rlx
> +DELIMITERS = "<.>" "<!>" "<?>" ;
Бул файлды толык алып тастайн ба?
негизи мен бул файлды коскан жок едим, негедир гитке салган кезимде автомат таризде косылып кеткен

2021-07-05 04:22 UTC, jonorthwash commented on uzb-kaa.rlx
> +DELIMITERS = "<.>" "<!>" "<?>" ;
Awa, alıp tastańız.  Bul fayl avtomat tárizde payda boladı—biraq dál sonlıqtan repoda bolmaw kerek.  `git`penen abay bolıw kerek, qosqıńız kelgen fayllardı ǵana qosıwǵa háreket qılıńız.

2021-07-14 16:47 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>joylashgan<s n="n"/></l>                   <r>jaylasqan<s n="n"/></r></p></e>
Bul zat esim emes, "joyla/jayla" degen etisliktiń forması.  Sózlerdiń tamırların ǵana kiritiw kerek.  Usı sózdin ústindegi sóz bul kózqarastan durıs, dúzletiw ǵana kerek.  "joyla" `v.iv` = "jayla" `v.iv`.

2021-07-14 16:53 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>umumiy<s n="n"/></l>               <r>ulıwma<s n="n"/></r></p></e>
Bul zat esimbe, yamasa sın esimbe?

2021-07-14 16:54 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>zichligi<s n="n"/></l>                  <r>Qısıqlıǵı<s n="n"/></r></p></e>
Tamırlardı ǵana qosıwǵa boladı.

2021-07-14 16:54 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>etish<s n="adv"/></l>                   <r>etiw<s n="adv"/></r></p></e>
Bul `adv`pe?  Tamırın qosıw kerek.

2021-07-14 16:55 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tashkil<s n="adv"/></l>                 <r>ornalastırıw<s n="adv"/></r></p></e>
Bul `adv`pe?

2021-07-14 16:55 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tomonidan<s n="adv"/></l>                 <r>tárepinen<s n="adv"/></r></p></e>
Tamırlardı ǵana qosıw kerek.

2021-07-14 16:55 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>turkumdagi<s n="adv"/></l>              <r>taypadaǵı<s n="adv"/></r></p></e>
Tamırlardı ǵana qosıw kerek.

2021-07-24 18:19 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>umumiy<s n="n"/></l>               <r>ulıwma<s n="n"/></r></p></e>
мениң оймша uliwma деген сөз бул sin esim , sin esim bolsa adj болама?

2021-07-24 18:32 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>etish<s n="adv"/></l>                   <r>etiw<s n="adv"/></r></p></e>
бул жерде etish -> etiw/qiliw тамыры ғо et болса маниси шыкпай калады

2021-07-29 04:51 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>joylashgan<s n="n"/></l>                   <r>jaylasqan<s n="n"/></r></p></e>
Jaqsı.  Endi `coop` degendi alıp tastaw kerek, eki jaǵınan.

2021-07-29 04:52 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>umumiy<s n="n"/></l>               <r>ulıwma<s n="n"/></r></p></e>
Awa, sın esim adj boladı.

2021-07-29 04:52 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>umumiy<s n="n"/></l>               <r>ulıwma<s n="n"/></r></p></e>
Umumiy degen sóz de solay bolsa kerek.

2021-07-29 04:53 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>zichlig<s n="n"/></l>                  <r>Qısıq<s n="n"/></r></p></e>
"zichlik" emespe?  Jáne sózlerdi úlken áriplermenen qospaw kerek, kisi yamasa jerdiń atı bolmasa.

2021-07-29 04:55 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>etish<s n="adv"/></l>                   <r>etiw<s n="adv"/></r></p></e>
Onda `"et" <v><tv>` = `"et" <v><tv>` bolıw kerek, yaǵnıy tamırımenen qosıw kerek.

2021-07-29 04:57 UTC, jonorthwash commented
Bul PRdı qabıl etiwge az qaldı!  Qalǵan surawlarımdı teksere alasız.

2021-08-05 15:39 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>bor<s n="v"/></l>                      <r>bar<s n="n"/></r></p></e>
Bunı düzlew kerek.

2021-08-08 14:00 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qoldi<s n="v"/></l>                   <r>qaldı<s n="v"/></r></p></e>
Bul tamır emesğo

2021-08-08 14:01 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
>  <e>       <p><l>tushirgi<s n="n"/></l>                 <r>túsirgi<s n="n"/></r></p></e>
Bul tamır emesğo.

2021-08-08 14:02 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>yozuvchi<s n="n"/></l>                 <r>jazıwchı<s n="n"/></r></p></e>
"jazıwshı" emespe?

2021-08-08 14:03 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>et<s n="v"/><s n ="tv"/></l>                   <r>et<s n="v"/></r></p></e>
Qaraqalpaqshasına `tv` degendi qosıw kerek.

2021-08-08 14:04 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qiziq<s n="adv"/></l>                  <r>qızıqlı<s n="adv"/></r></p></e>
Bul `adj` bolmayma?

2021-08-08 14:04 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tashkil<s n="adv"/></l>                 <r>ornalastırıw<s n="adv"/></r></p></e>
Bunı túsingen joqpan.

2021-08-08 14:05 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tayyor<s n="adj"/><s n="tv"/></l>             <r>tayar<s n="adj"/></r></p></e>
Nege `tv`?

2021-08-08 14:05 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tomchi<s n="n"/></l>                 <r>tamshi<s n="n"/></r></p></e>
"tamshı" emespe?

2021-08-08 14:07 UTC, jonorthwash requested changes
`dix`tegi qateliklerdi durıslap, `rlx`ti óshiriw kerek.

2021-08-08 15:17 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tomchi<s n="n"/></l>                 <r>tamshi<s n="n"/></r></p></e>
аа дурыс, қателик кетип калыпты

2021-08-08 15:18 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tashkil<s n="adv"/></l>                 <r>ornalastırıw<s n="adv"/></r></p></e>
tashkillashtirish - организовать болады на русском

2021-08-08 15:18 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qiziq<s n="adv"/></l>                  <r>qızıqlı<s n="adv"/></r></p></e>
ауа, adj болады қателесиппен

2021-08-08 15:30 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tayyor<s n="adj"/><s n="tv"/></l>             <r>tayar<s n="adj"/></r></p></e>
тамыры болған сон tv қойу керек емеспа? себеби tayyorlash, tayyorladi, tayyorlamoqda болып өзгередиго

2021-08-08 15:41 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tashkil<s n="adv"/></l>                 <r>ornalastırıw<s n="adv"/></r></p></e>
мениң ойымша бул tashkil qilish болса verb болады

2021-08-08 15:41 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tashkil<s n="adv"/></l>                 <r>ornalastırıw<s n="adv"/></r></p></e>
ямаса бул сөзди алып тастағаным махулма?

2021-08-08 21:08 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tashkil<s n="adv"/></l>                 <r>ornalastırıw<s n="adv"/></r></p></e>
Onda "tashkillashtir" `v.tv` = "ornalastır" `v.tv` bolsa kerek.

2021-08-08 21:10 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
>  <e>       <p><l>tayyorlash<s n="adv"/></l>             <r>tayarlaw<s n="adv"/></r></p></e>
Bul "tayyorla `v.tv`" = "tayarla `v.tv`" degen durıs.

2021-08-08 21:11 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tayyor<s n="adj"/><s n="tv"/></l>             <r>tayar<s n="adj"/></r></p></e>
"tayyorla" degen etislik astında.  Bul "tayyor" degen sın esim bolsa kerek.

2021-08-19 18:13 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>bor<s n="v"/></l>                      <r>bar<s n="n"/></r></p></e>
ekewi `<iv>` bolıw kerek

2021-08-19 18:14 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qoldi<s n="v"/></l>                   <r>qaldı<s n="v"/></r></p></e>
Bunı tamır qılıw kerek.  `qol<v><iv>` = `qal<v><iv>`

2021-08-19 18:15 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
>  <e>       <p><l>tushirgi<s n="n"/></l>                 <r>túsirgi<s n="n"/></r></p></e>
`tushintir<v><tv>` = `túsindir<v><tv>`

2021-08-19 18:15 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>yozuvchi<s n="n"/></l>                 <r>jazıwchı<s n="n"/></r></p></e>
"jazıwshı" boladıǵo..

2021-08-19 18:25 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tashkil<s n="adv"/></l>                 <r>ornalastırıw<s n="adv"/></r></p></e>
Bunı da bitiriw kerek.

2021-08-19 18:26 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tayyor<s n="adj"/><s n="tv"/></l>             <r>tayar<s n="adj"/></r></p></e>
Jańa bos orın bolıp kettipti, "tasviqiy" degen sózden keyin.

2021-08-19 18:27 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tayyor<s n="adj"/><s n="tv"/></l>             <r>tayar<s n="adj"/></r></p></e>
Sodan basqa, `tv` degendi alıp tastaw kerek.

2021-08-19 18:27 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>tomchi<s n="n"/></l>                 <r>tamshi<s n="n"/></r></p></e>
Bul da qayttan nadurıs bolıp ketipti...

2021-08-20 17:55 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>chiqish<s n="v"/><s n="tv"/></l>                  <r>shıǵıw<s n="v"/><s n="tv"/></r></p></e>
Bul burıs bolǵan...  "chiq"/"shıq" degen etislikti qosqıńız kelse, jańa qatar qosıw kerek, bunı `<n>` dep qaldırıp.

2021-08-20 17:56 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>boshlash<s n="v"/><s n="iv"/><s n="coop"/></l><r>baslaw<s n="v"/><s n="iv"/><s n="coop"/></r></p></e>
Unǵı/tamır ǵana boladı.  "boshla" = "basla", esqanday `coop` keregi joq.

2021-08-20 17:58 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>siz<s n="adj"/></l>        <r>siz<s n="adj"/></r></p></e>
Bul ne?

2021-08-20 17:59 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>usti<s n="n"/></l>                   <r>ústi<s n="n"/></r></p></e>
Bul "ust"="úst" degen ǵana bolıw kerek.

2021-08-20 18:00 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>yorish<s n="v"/></l>                   <r>jarıw<s n="v"/></r></p></e>
Uńǵıları/tamırları ǵana...

2021-08-20 18:02 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qiziqqon<s n="adv"/></l>               <r>qızıqqan<s n="adv"/></r></p></e>
Bul `adv` bolmaydı dep oylayman.  Etisliktiń forması ǵanaǵo..?  Ornına `qızıq<v><iv>` dep qossańız bolsa kerek.

2021-08-20 18:03 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +n="adv"/></r></p></e>
jańa sızıq bolıp ketipti...

2021-08-20 18:03 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>bu<s n="det"/><s n="dem"/> <s n="prn"/></l>          <r>bul<s n="det"/><s n="dem"/><s n="prn"/></r></p></e>
`<prn>` degendi alıp taslańız...

2021-08-20 18:13 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>usti<s n="n"/></l>                   <r>ústi<s n="n"/></r></p></e>
бул жерде, негизи ust деген тамыр жоқ, ustoz ҳәм usta булар өз алдына тамыр болып табылады, тек ғана usti дегенде қателик кеткен болуы мумкин, usti - жоқары тарепи , яғний ustida - on, деп аудармаланады

2021-08-20 18:18 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qiziqqon<s n="adv"/></l>               <r>qızıqqan<s n="adv"/></r></p></e>
qiziq - verb бола алмайдығы менимше, бул жерде adj дурыс емеспа? себеби қызық - қандай деген сорауға жууап береди

2021-08-20 18:19 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +n="adv"/></r></p></e>
бул не дегени? онша тусинбедим

2021-08-22 18:32 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +n="adv"/></r></p></e>
Bul jerdegi jańa strochkanı alıp taslań.

2021-08-22 18:33 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +n="adv"/></r></p></e>
Astında, tasviqiy degen sóz ushın (fayl ózgergende kommentariya jıljıy beredi..).

2021-08-22 18:35 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qiziqqon<s n="adv"/></l>               <r>qızıqqan<s n="adv"/></r></p></e>
Men qiziqqon = qızıqqan degen sózdi aytıp atırman (kommentariya jıljıp ketipti).  "Qızıǵıp" degen sóz qollanılama?

2021-08-22 18:37 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>usti<s n="n"/></l>                   <r>ústi<s n="n"/></r></p></e>
"úst" degen tamır jalǵız qollanılmawı múmkin, biraq mınday degen tamır bar.  "usti" dep kirgizseń islemeydi.  Analizatorda bılay:
```
^ústinde/úst<n><px3sp><loc>/úst<n><px3sp><loc>+e<cop><aor><p3><pl>/úst<n><px3sp><loc>+e<cop><aor><p3><sg>$
```

2021-08-22 18:39 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>boshlash<s n="v"/><s n="iv"/></l><r>baslaw<s n="v"/><s n="iv"/></r></p></e>
"boshlash" jáne "baslaw" zat esimlerǵo (`n`).  Etisliklerdi qosıw ushın, tamırları kerek: "boshla" jáne "basla".  Ekewin qosayıqpa?

2021-08-22 18:42 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>oldindan<s n="adv"/></l>               <r>aldınnan<s n="adv"/></r></p></e>
"old" = "ald" degen tamırdı qossańız, "oldiga", "oldin", "oldinda", "oldindan", "oldinga", "oldingi" degen formalardı alıp taslawǵa boladı.

2021-08-22 18:43 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>oldindan<s n="adv"/></l>               <r>aldınnan<s n="adv"/></r></p></e>
Bul "úst" degen tamırǵa oqsas: negizinde sonday forma qollanılmaydı, biraq sol tamırmenen kóp forma túziledi.

2021-08-22 18:43 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>foydalan<s n="v"/><s n="iv"/><s n="pass"/></l>              <r>paydalan<s n="v"/><s n="iv"/><s n="pass"/></r></p></e>
"foydalan" `v.tv` = "paydalan" `v.tv`

2021-08-22 18:45 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>chiq<s n="v"/><s n="tv"/></l>                  <r>shıq<s n="v"/><s n="tv"/></r></p></e>
chiq/shıq `v.iv` bolıw kerek.  bir nárseNİ shıqpaydı...

2021-08-22 18:52 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>boshlash<s n="v"/><s n="iv"/></l><r>baslaw<s n="v"/><s n="iv"/></r></p></e>
хазир, өзгертемен

2021-08-22 20:35 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>old<s n="v"/><s n="iv"/></l>                   <r>ald<s n="n"/><s n="iv"/></r></p></e>
`v` emesǵo, `n` ǵana

2021-08-22 20:36 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> -<e>       <p><l>boshlangʻich<s n="n"/></l>             <r>baslanǵısh<s n="n"/></r></p></e>
"baslanǵısh" degen `adj` boladı, taslamawǵa boladı.

2021-08-22 20:40 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>foydalan<s n="v"/><s n="iv"/><s n="pass"/></l>              <r>paydalan<s n="v"/><s n="iv"/><s n="pass"/></r></p></e>
astında solay eken.  bul jerder foydalanish=paydalanıw degen zat esimdi qaldırıń, польза degen mániste...

2021-08-22 20:40 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>hisobla<s n="v"/><s n="iv"/></l>                  <r>esapla<s n="n"/><s n="iv"/></r></p></e>
But `tv` boladı sıyaqlı.

2021-08-22 20:46 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qiziqqon<s n="adv"/></l>               <r>qızıqqan<s n="adv"/></r></p></e>
мен китапты қызығып охыдым, деп айтуға болады

2021-08-22 20:58 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>bajarish<s n="v"/><s n="iv"/><s n="coop"/></l><r>orınlaw<s n="v"/><s n="iv"/><s n="coop"/></r></p></e>
`n` emespe?

2021-08-22 20:59 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>bajar<s n="v"/><s n="iv"/></l>         <r>orınlaw<s n="v"/><s n="iv"/></r></p></e>
tamırı `orınla` boladıǵo

2021-08-22 20:59 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> -<e>       <p><l>chiqarish<s n="v"/><s n="iv"/><s n="coop"/></l><r>shıǵarıw<s n="v"/><s n="iv"/><s n="coop"/></r></p></e>
"chiqarish" = "shıǵarıw" `n` boladı.  Qayttan qosıń.

2021-08-22 21:01 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>foydalan<s n="tv"/><s n="tv"/></l>    <r>paydalan<s n="tv"/><s n="tv"/></r></p></e>
`v.tv`...

2021-08-22 21:02 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>qiziqqon<s n="adv"/></l>               <r>qızıqqan<s n="adv"/></r></p></e>
onda "qızıq" etislik boladıǵo...

2021-08-22 21:04 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> -<e>       <p><l>chiqarish<s n="v"/><s n="iv"/><s n="coop"/></l><r>shıǵarıw<s n="v"/><s n="iv"/><s n="coop"/></r></p></e>
вывод mániste, menimshe...

2021-08-22 21:30 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>foydalan<s n="tv"/><s n="tv"/></l>              <r>paydalan<s n="tv"/><s n="tv"/></r></p></e>
`tv.tv` emes, `v.tv`

2021-08-22 21:32 UTC, jonorthwash commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>oʻrinlash<s n="n"/>                    </l><r>orınlaw<s n="n"/></r></p></e>
Bunı da feyil mánisinde qosıwǵa boladı.  "oʼrinla" `v.tv` = "orınla" `v.tv`

2021-08-22 21:33 UTC, Zigfruid commented on apertium-uzb-kaa.uzb-kaa.dix
> +<e>       <p><l>oʻrinlash<s n="n"/>                    </l><r>orınlaw<s n="n"/></r></p></e>
cous ты алып тастайнба?

2021-08-24 21:25 UTC, jonorthwash approved these changes
Bunı házir qabıllayman, qalǵan úsh másele ushın jańa PR asha alamız dep oylayman.

2021-08-24 21:27 UTC, merged